In [2]:
import numpy as np

In [3]:
import pandas as pd

In [20]:
data=np.random.random((4,3))
data
data[0]

array([[0.3397358 , 0.60533317, 0.24148823],
       [0.02723957, 0.81893604, 0.25065786],
       [0.06791271, 0.96188284, 0.64580954],
       [0.08527759, 0.27760384, 0.48485799]])

In [22]:
df=pd.DataFrame(data)
df

0         1         2
0  0.339736  0.605333  0.241488
1  0.027240  0.818936  0.250658
2  0.067913  0.961883  0.645810
3  0.085278  0.277604  0.484858

In [6]:
df[0]
#column olarak getirdi dikkat et

0   -0.191355
1    0.545915
2    1.726013
3   -0.362527
Name: 0, dtype: float64

In [26]:
df[0][1]

0.02723956849133502

In [25]:
liste=[["a","b","c"],["d","e","f"],["g","h","i"]]
df2=pd.DataFrame(data=liste)
df2

0  1  2
0  a  b  c
1  d  e  f
2  g  h  i

In [28]:
df2[2][0]
#2.column 0.row getirdi dikkat et. Dataframelerde indexlerken col row şeklindeymiş demek ki

'c'

In [32]:
df1=pd.DataFrame(data,index=["atil","zeynep","atlas","anil"],columns=["maas","yas","calisma saati"])

df3=pd.DataFrame(data=liste,index=["1.","2.","3."],columns=["1.","2.","3."])
#index -> row
#column da column

df1

maas       yas  calisma saati
atil    0.339736  0.605333       0.241488
zeynep  0.027240  0.818936       0.250658
atlas   0.067913  0.961883       0.645810
anil    0.085278  0.277604       0.484858

In [33]:
df1["maas"]

atil      0.339736
zeynep    0.027240
atlas     0.067913
anil      0.085278
Name: maas, dtype: float64

In [39]:
df1["maas"]["atil"]

0.33973579937075316

In [37]:
array1=np.random.randint(0,10,size=(3,3))
array1

array([[9, 7, 6],
       [5, 1, 3],
       [2, 1, 4]])

In [38]:
array1[[0,2]]

array([[9, 7, 6],
       [2, 1, 4]])

In [10]:
df1[["yas","maas"]]
#ayrı bi list parantezi açıp birden fazla column da aynı anda gösteririz ve bu mevcut df değiştirmez
#numpy arraylerdeki gibi burada da aynısını yapabiliyoruz

yas      maas
atil    1.946153 -0.191355
zeynep  0.841279  0.545915
atlas  -0.107333  1.726013
anil   -0.956688 -0.362527

In [11]:
df1

maas       yas  calisma saati
atil   -0.191355  1.946153      -0.010463
zeynep  0.545915  0.841279      -1.285978
atlas   1.726013 -0.107333      -0.147287
anil   -0.362527 -0.956688      -0.077084

In [40]:
#sadece bir row un verilerini alcam
df1.loc["atil"]

maas             0.339736
yas              0.605333
calisma saati    0.241488
Name: atil, dtype: float64

In [42]:
df3.loc["1."]

1.    a
2.    b
3.    c
Name: 1., dtype: object

In [47]:
df2.loc[2]

0    g
1    h
2    i
Name: 2, dtype: object

In [48]:
df1.loc[["atil","zeynep"]]
#numpy arraylarde arr[[0,4]] yazınca 0. ve 4.rowları alıyordu. Burada da aynısını yapabiliyoruz

maas       yas  calisma saati
atil    0.339736  0.605333       0.241488
zeynep  0.027240  0.818936       0.250658

In [52]:
df3.loc[["3.","1."]]
#sadece belirttiğim rowları seçtim

1. 2. 3.
3.  g  h  i
1.  a  b  c

In [53]:
df1

maas       yas  calisma saati
atil    0.339736  0.605333       0.241488
zeynep  0.027240  0.818936       0.250658
atlas   0.067913  0.961883       0.645810
anil    0.085278  0.277604       0.484858

In [14]:
#satırları index bazlı da çağırabilirim iloc dersem
df1.iloc[0]

maas            -0.191355
yas              1.946153
calisma saati   -0.010463
Name: atil, dtype: float64

In [55]:
df3

1. 2. 3.
1.  a  b  c
2.  d  e  f
3.  g  h  i

In [59]:
df3.iloc[2]
#df[] şeklinde belirtirsem column halinde alır
#df.loc[] veya df.loc[[]] şeklinde belirtirsem row halinde alır
# df.iloc[] şeklinde yaparsak da index bazlı olarak rowları gösterebiliyoruz

1.    g
2.    h
3.    i
Name: 3., dtype: object